 ---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)

p19t14 <- read_csv("~/Desktop/Stat380/CopyOfp19t14.csv")
p19t14 <- p19t14%>%
  select(-'Bureau of Justice Statistics')

p19t14_flip <- as.data.frame(t(p19t14))

```
```{r}
#library(readr)
#CopyOfp19t14 <- read_csv("~/Desktop/Stat380/CopyOfp19t14.csv")
#View(CopyOfp19t14)
```

```{r}
p19t14_flip <- p19t14_flip %>%
  select(-c("V1","V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V33", "V34", "V35", "V36", "V37", "V38", "V39", "V40"))
p19t14_flip
```

```{r}
names(p19t14_flip) <- as.matrix(p19t14_flip[1, ])
p19t14_flip <- p19t14_flip[-1, ]
p19t14_flip[] <- lapply(p19t14_flip, function(x) type.convert(as.character(x)))
View(p19t14_flip)
```

```{r}
colnames(p19t14_flip)[1] <- 'Characteristic'
colnames(p19t14_flip)[3] <- 'Violent Crime Totals' #Murder, Negligent manslaughter, Rapse/sexual assualt, robbery, aggravated/simple assault, other
colnames(p19t14_flip)[10] <- 'Property Crime Totals' #Burglary, Larcenty/theft, Motor-vehicle theft, fraud, other
colnames(p19t14_flip)[16] <- 'Drug Crime Totals' #Possession, other
colnames(p19t14_flip)[19] <- 'Public Order Crime Totals' #weapons, dui/dwi, other
colnames(p19t14_flip)[23] <- 'Other/Unspecified Crime Totals'
```


```{r}
p19t14_flip %>%
  select(Characteristic, Total, `Violent Crime Totals`, `Property Crime Totals`,`Drug Crime Totals`, `Public Order Crime Totals`, `Other/Unspecified Crime Totals` )
```


```{r}
table1014_idea <- map_df(p19t14_flip1, ~gsub(",","", .x))
table1014_idea2 <- as.data.frame(sapply(table1014_idea, as.numeric ))
#table1014_idea2
characteristic <- c("All prisoners", "Male", "Female", "White/b", "Black/b", "Hispanic")
table1014_idea2$Characteristic <- characteristic
View(table1014_idea2)
```

```{r}
library(esquisse)
```

```{r}
#esquisser(table1014_idea2)
```

```{r}
table1014 <- 
  table1014_idea2 %>% #select(`White/a`, `Black/a`, Hispanic, `Other/a,b`) %>%
  pivot_longer(., cols = c(Total, `Violent Crime Totals`, `Property Crime Totals`, `Drug Crime Totals`, `Public Order Crime Totals`), names_to = "Crime Totals", values_to = "Count")
table1014
```

```{r}
esquisser(table1014)
```

```{r}
table1014_2 <- 
  table1014_idea2 %>% 
  select(Characteristic, Total, `Violent Crime Totals`, `Property Crime Totals`, `Drug Crime Totals`, `Public Order Crime Totals`) 
table1014_2_flip <-
  as.data.frame(t(table1014_2))
table1014_2_flip
```

```{r}
#delete row
#table1014_2_flip<-table1014_2_flip[-1, ]
names(table1014_2_flip) <- as.matrix(table1014_2_flip[1, ])
table1014_2_flip <- table1014_2_flip[-1, ]
table1014_2_flip[] <- lapply(table1014_2_flip, function(x) type.convert(as.character(x)))
table1014_2_flip
```

```{r}
data1 <- table1014_2_flip                                           # Duplicate example data
data1$row_names <- row.names(data1)                     # Apply row.names function
data1  
```









#below works but doesnt take into account the offenses

```{r}
table <-
  data1 %>%
  pivot_longer(., cols = c(`All prisoners`, Male, Female), names_to = "Gender", values_to = "Count")
table
```

```{r}
table1_i <-
  table %>%
  pivot_longer(., cols = c(`White/b`, `Black/b`, Hispanic), names_to = "Race", values_to = "Race_Count")
table1_i
```
```{r}
#esquisser(table1_i
#library(dplyr)
#library(ggplot2)

table1_i %>%
 filter(!(row_names %in% "Total")) %>%
 filter(!(Gender %in% "All prisoners")) %>%
 ggplot() +
 aes(x = Race, weight = Race_Count) +
 geom_bar(fill = "#006d2c") +
 labs(x = "Race", y = "Count", title = "Number of Sentenced Prisoners by Race and Type of Offense Totals") +
 theme_bw() +
 facet_wrap(vars(row_names))

table1_i %>%
 filter(!(row_names %in% "Total")) %>%
 filter(!(Gender %in% "All prisoners")) %>%
 ggplot() +
 aes(x = Gender, weight = Count) +
 geom_bar(fill = "#47039f") +
 labs(x = "Gender", y = "Count", title = "Number of Sentenced Prisoners by Gender and Type of Offense Totals") +
 theme_bw() +
 facet_wrap(vars(row_names))

```


```{r}
#esquisser(table1_i
#library(dplyr)
#library(ggplot2)

table1_i %>%
 filter(!(Gender %in% "All prisoners")) %>%
 ggplot() +
 aes(x = Race_Count, y = Count, fill = Race, colour = Race) +
 geom_line(size = 1L) +
 scale_fill_hue() +
 scale_color_hue() +
 labs(x = "Race Count", y = "Gender Count", title = "Number of Sentenced Prisoners by Offense, Sex, and, Race ") +
 theme_bw() +
 facet_wrap(vars(Gender))
)
```


```{r}
green <- 
  data1 %>%
  select()
```

```{r}
pairs(data1)
```





### Pairs unsupervised? 
```{r}
#pairs(table1_i)
```



#state data only ...table 10 uses state and federal data