---
title: "R Notebook"
output: html_notebook
---


# table 14: Table 14. Number of sentenced prisoners under the jurisdiction of state correctional authorities, by most serious offense, sex, and race or ethnicity, December 31, 2018
```{r}
library(tidyverse)
library(janitor)

p19t14 <- read_csv("~/Desktop/Stat380/CopyOfp19t14.csv")
p19t14 <- p19t14%>%
  select(-'Bureau of Justice Statistics')

p19t14_flip1 <- as.data.frame(t(p19t14))

```
```{r}
#library(readr)
#CopyOfp19t14 <- read_csv("~/Desktop/Stat380/CopyOfp19t14.csv")
#View(CopyOfp19t14)
```

```{r}
p19t14_flip1 <- p19t14_flip1 %>%
  select(-c("V1","V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9", "V33", "V34", "V35", "V36", "V37", "V38", "V39", "V40"))
p19t14_flip1
```

```{r}
names(p19t14_flip1) <- as.matrix(p19t14_flip1[1, ])
p19t14_flip1 <- p19t14_flip1[-1, ]
p19t14_flip1[] <- lapply(p19t14_flip1, function(x) type.convert(as.character(x)))
View(p19t14_flip1)
```

```{r}
colnames(p19t14_flip1)[1] <- 'Characteristic'
colnames(p19t14_flip1)[3] <- 'Violent Crime Totals' #Murder, Negligent manslaughter, Rapse/sexual assualt, robbery, aggravated/simple assault, other
colnames(p19t14_flip1)[9] <- 'Other Violent Crimes'
colnames(p19t14_flip1)[10] <- 'Property Crime Totals' #Burglary, Larcenty/theft, Motor-vehicle theft, fraud, other
colnames(p19t14_flip1)[15] <- 'Other Property Crimes'
colnames(p19t14_flip1)[16] <- 'Drug Crime Totals' #Possession, other
colnames(p19t14_flip1)[18] <- 'Other Drug Crimes'
colnames(p19t14_flip1)[19] <- 'Public Order Crime Totals' #weapons, dui/dwi, other
colnames(p19t14_flip1)[22] <- 'Other Public Order Crimes'
colnames(p19t14_flip1)[23] <- 'Other/Unspecified Crime Totals'
```


```{r}
p19t14_flip1 %>%
  select(Characteristic, Total, `Violent Crime Totals`, `Property Crime Totals`,`Drug Crime Totals`, `Public Order Crime Totals`, `Other/Unspecified Crime Totals` )
```

```{r}
table1014_idea <- map_df(p19t14_flip1, ~gsub(",","", .x))
table1014_idea2 <- as.data.frame(sapply(table1014_idea, as.numeric ))
#table1014_idea2
characteristic <- c("All prisoners", "Male", "Female", "White/b", "Black/b", "Hispanic")
table1014_idea2$Characteristic <- characteristic
View(table1014_idea2)

```

```{r}
library(esquisse)
```

```{r}
esquisser(table1014_idea2)

```
```{r}
#table1014 <- 
  table1014_idea2 %>% #select(`White/a`, `Black/a`, Hispanic, `Other/a,b`) %>%
  pivot_longer(., cols = c(Total, `Violent Crime Totals`, `Property Crime Totals`, `Drug Crime Totals`, `Public Order Crime Totals`), names_to = "Crime Totals", values_to = "Count")
table1014
```

```{r}
esquisser(table1014)
```

```{r}
table1014_2 <- 
  table1014_idea2 %>% 
  select(Characteristic, Total, `Violent Crime Totals`, `Property Crime Totals`, `Drug Crime Totals`, `Public Order Crime Totals`) 
table1014_2
```

```{r}
table1014_2_flip <-
  as.data.frame(t(table1014_2))
table1014_2_flip
```

```{r}
#delete row
#table1014_2_flip<-table1014_2_flip[-1, ]

names(table1014_2_flip) <- as.matrix(table1014_2_flip[1, ])
table1014_2_flip <- table1014_2_flip[-1, ]
table1014_2_flip[] <- lapply(table1014_2_flip, function(x) type.convert(as.character(x)))
table1014_2_flip
```


```{r}
table <-
  table1014_2_flip %>%
  pivot_longer(., cols = c(`All prisoners`, Male, Female), names_to = "Gender", values_to = "Count")
table
```
```{r}
table1 <-
  table %>%
  pivot_longer(., cols = c(`White/b`, `Black/b`, Hispanic), names_to = "Race", values_to = "Race_count")
table1
```






```{r}
library(esquisse)
```


```{r}
esquisser(table1
library(dplyr)
library(ggplot2)
```

```{r}

table1 %>%
 filter(!(Gender %in% "All prisoners")) %>%
 ggplot() +
 aes(x = Count, y = Race_count, fill = Race, colour = Race) +
 geom_area(size = 1L) +
 scale_fill_hue() +
 scale_color_hue() +
 labs(x = "Race Count", y = "Gender Count", title = "Comparison of Male and Female Prisoners") +
 theme_bw() +
 facet_wrap(vars(Gender))
)
```

























```{r}

%>%
  pivot_longer(., cols = c(Total, `Violent Crime Totals`, `Property Crime Totals`, `Drug Crime Totals`, `Public Order Crime Totals`), names_to = "Crime Totals", values_to = "Count")
table1014
```



#unsupervised learning...clustering
```{r}
library(tidyverse)
library(cluster)
library(factoextra)
```


## Combine the two tables, 10 and 14, to compare 


