---
title: "New York Data"
output: html_notebook
---



```{r}
library(tidyverse)

NYdata <- read_csv("seven-major-felony-offenses-2000-2021.csv")

years <- c('offense','2000', '2001', '2002', '2003', '2004', '2005','2006','2007','2008','2009', '2010','2011','2012','2013', '2014','2015','2016','2017','2018','2019','2020','2021')

names(NYdata)<-years
NYdata_cleaned<-NYdata %>% slice(-c(1, 2, 3, 4, 13,14,15,16,17,18,19,20))

View(NYdata_cleaned)

```

```{r}
NYdata_cleaned2<-
  NYdata_cleaned%>%
  pivot_longer(cols = starts_with('20'), names_to = 'Year', values_to = 'crime_count')
```

```{r}
#bar graph of MURDER & NON-NEGL. MANSLAUGHTER over time(year) from 2000 to 2021 in New York
NYdata_cleaned2%>%
  filter(offense == 'MURDER & NON-NEGL. MANSLAUGHTER')%>%
  ggplot(aes(x = Year, y = crime_count))+
  geom_col(fill = 'lightgreen')
```

```{r}
#bar graph of RAPE over time(year) from 2000 to 2021 in New York
NYdata_cleaned2%>%
  filter(offense == 'RAPE')%>%
  ggplot(aes(x = Year, y = crime_count))+
  geom_col(fill = 'pink')
```



# NYPD Arrests data 2015-2019:
```{r}
NYPD <- read_csv("NYPD_Arrests_Data_2017_2019.csv")

```

```{r}
NYPD_Arrests<-
  NYPD%>%
  select('ARREST_KEY','ARREST_DATE','PD_DESC','OFNS_DESC','ARREST_BORO','JURISDICTION_CODE','AGE_GROUP','PERP_SEX','PERP_RACE')

```



```{r}
NYPD_Arrests$OFNS_DESC<-ifelse(grepl("ASSAULT", NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'ASSAULT', NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('OFFENSES AGAINST THE PERSON',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'ASSAULT',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('PROSTITUTION',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'SEX CRIMES',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('LARCENY',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'LARCENY AND THEFT',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('THEF',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'LARCENY AND THEFT',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('ROBBERY',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'LARCENY AND THEFT',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('FRAUD',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'FRAUD',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('WEA',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'WEAPONS AND TOOLS',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('TOOL',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'WEAPONS AND TOOLS',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('MURDER',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'MURDER',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('CHILD',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'OFFENSES RELATED TO CHILDREN',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('HOMICIDE-NEGLIGENT',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'HOMICIDE-NEGLIGENT',NYPD_Arrests$OFNS_DESC)
NYPD_Arrests$OFNS_DESC<-ifelse(grepl('DRUG',NYPD_Arrests$OFNS_DESC, fixed = TRUE), 'DRUGS AND RELATED',NYPD_Arrests$OFNS_DESC)
```

```{r}
offense = c('ASSAULT','SEX CRIMES','LARCENY AND THEFT','RAPE', 'MURDER','DRUGS AND RELATED','HOMICIDE-NEGLIGENT')
NYPD_filtered<-
  NYPD_Arrests%>%
  filter(OFNS_DESC == offense)


```


```{r}
#boxplot by race and arrest counts
NYPD_filtered%>%
  group_by(OFNS_DESC, PERP_RACE)%>%
  summarise(arrest_count = n())%>%
  ggplot(aes(x = arrest_count))+
  geom_boxplot()+
  facet_grid(rows = vars(PERP_RACE))
```

```{r}

```

