---
title: "p19t14"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)

p19t14 <- read_csv("p19t14.csv")
p19t14 <- p19t14%>%
  select(-'Bureau of Justice Statistics')

p19t14_flip <- as.data.frame(t(p19t14))

```


```{r}
p19t14_flip <-p19t14_flip%>%
  select('V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26','V27', 'V28', 'V29', 'V30', 'V31', 'V32')
  
```

```{r}
names(p19t14_flip) <- lapply(p19t14_flip[1, ], as.character)
p19t14_flip <- p19t14_flip[-1,]

#All prisoners,gender, ethnicity
```


```{r}
p19t14_cleaned <- 
  p19t14_flip%>%
  clean_names()%>%
  select(-na_2, -na_3, -na_4, -na_5, -na_6)%>%
  rename('Features'='na')
```

```{r}
p19t14_cleaned2 <-p19t14_cleaned[,-1]
rownames(p19t14_cleaned2)<-p19t14_cleaned[,1]
```


```{r}
clean_df <- map_df(p19t14_cleaned2, ~ gsub(",", "", .x))

```

```{r}
clean_df <- as.data.frame(sapply(clean_df, as.numeric))
```

```{r}
clean_df%>%
  ggplot(aes(x = murder_c))+
  geom_boxplot()
```


