```
Cleaning table p19t08

```

```{r}
install.packages("ftExtra")
```

1) Load packages

```{r}
library(tibble)
library(readr)
library(ftExtra)
library(dplyr)
```


2) Read csv file
```{r}

p19t08 <- read_csv("p19t08.csv")
p19t08
```


3) remove rows 1~9 and rows 65~84
```{r}

df <- p19t08[-c(1:9, 65:84),]

df

```

4) split into two data frames: Admssions and Releases

- Admissions

```{r}
df_Admission <- df[, c(1:8)]
df_Admission
```

-Releases
```{r}

# Create new table from df column 10 to 15
df_Releases <- df[, c(10:15)]

# Add the first and second column to Releases Table as well.
df_Releases <-add_column(df[,c(1,2)],df_Releases)
df_Releases

```



5) Change Header names and drop rows

- a) Admission
```{r}

colnames(df_Admission) <- df_Admission[2, ]   # Convert second row to header
df_Admission <- df_Admission[-c(1,2), ]       # Remove first and second row

df_Admission

```

- b) Releases
```{r}
colnames(df_Releases) <- df_Releases[2, ]          # Convert second row to header
df_Releases <- df_Releases[-c(1,2), ]              # Remove first and second row

df_Releases

```


6) Remove irrelevant columns/ features

```{r}
df_Admission <- df_Admission[,-c(6) ]
df_Releases <- df_Releases[,-c(6) ]    

View(df_Admission)
View(df_Releases)
```




